export const studentColumns = {
  no: { no: 0, name: "No" },
  section: { no: 1, name: "Section" },
  grade: { no: 2, name: "Grade" },
  strand: { no: 3, name: "Strand" },
  gender: { no: 4, name: "Gender" },
  lrnNo: { no: 5, name: "LRN No" },
  lastName: { no: 6, name: "Last Name" },
  firstName: { no: 7, name: "First Name" },
  middleName: { no: 8, name: "Middle Name" },
  birthdate: { no: 9, name: "Birthdate" },
  age: { no: 10, name: "Age" },
  religion: { no: 11, name: "Religion" },
  currentAddress: { no: 12, name: "Current Address" },
  guardianLastName: { no: 13, name: "Guardian Last Name" },
  guardianFirstName: { no: 14, name: "Guardian First Name" },
  contactNo: { no: 15, name: "Contact No" },
  psa: { no: 16, name: "PSA" },
  card: { no: 17, name: "Card" },
  form137: { no: 18, name: "Form 137" },
  previousSchool: { no: 19, name: "Previous School" },
  previousSchoolNameAdviser: { no: 20, name: "Previous School Name/Adviser" },
  previousSchoolSection: { no: 21, name: "Previous School Section" },
};
